### ISSUE TITLE
Investigate whether to run nodejs-ipfs, orbitdb instances, and address-tracker on the same server instance

### ISSUE THREAD

**Issue by oed** [uport-project/3box-hash-server#14]
Key thing to note here is that ipfs and orbitdb can't be running on our current serverless architechture, since they require a continuous connection to the ipfs p2p network.

Create new stories as needed.

**Comment by c-castillo** [comment]
Costs breakdown:

dApps: Since they are deployed as static js+html+css, the only thing that aws charges is storage + bandwidth. It is definitely the way to go for static sites (S3 is cheaper than EC2)

Hash server: API Gateway has a free tier of 1M calls per month free, then it is 3.50 per million calls. Note this is only for calls to the `hash|address` server, not the orbitDB instances themselves. So, changing lambda  at this point makes no sense, even if we scale of thousands of customers

OrbitDB and IPFS instances: A `t3.small` instance costs $15/month, if we create a cluster of 2 orbitdb instances and 2 ipfs instances it costs USD 60/mo.
Each time we want to scale this cluster, it costs 30USD to add one more orbitdb and ipfs instance.

**Comment by oed** [comment]
@c-castillo I have a bunch of questions :) 
1. What would be the main advantage of not running ipfs + orbitdb on the same instance?
2. The `address-server` needs to send orbitAddresses to the orbitdb instance to pin. I guess authentication wouldn't be an issue here? (i.e. only the `address-server` can send orbitAddresses` to be pinned)
3. I guess it makes sense to scale in the following way (tell me if I'm wrong):
  * Add orbitdb + ipfs instance (separate or on the same instance)
  * Each orbitdb instance has a subset of 3box orbitAddresses that it keeps track of
  * The `address-server` knows which instance to pin which addresses on

**Comment by c-castillo** [comment]
@oed 

1) Probably I would say bandwidth but since they are in the same data center the latency difference won't be an issue.
2) We can whitelist domains or put them under the same subnet.
3) You mean something like sharding? Yes, we can partition the data like that or having read-only instances and write-only instances. Any of those (or all of those) can be implemented when scalability starts to be an issue.

**Comment by oed** [comment]
@c-castillo 👍 
1. Our client (3boxjs) would only communicate with the orbitdb instances though ipfs-pubsub, so running them on the same aws instance would not consume more bandwidth. (or are you talking about compute bandwith?)

**Comment by c-castillo** [comment]
@oed Yes, that's right. AWS doesn't charge for bandwidth inside the virtual network either, so it doesn't matter.
